<?php

/**
 * Nạp config phục vụ cho cache nếu có
 */

//
if (defined('EB_MY_CACHE_CONFIG') && is_file(EB_MY_CACHE_CONFIG)) {
    include EB_MY_CACHE_CONFIG;
}
defined('EB_REDIS_CACHE') || define('EB_REDIS_CACHE', false);

//
// include __DIR__ . '/DbCache.php';
// include __DIR__ . '/RedisCache.php';

/**
 * Kiểm tra hạn cache, mặc định là 12 tiếng
 */
function WGR_cache_expire($path, $t = 43200)
{
    if ($t > 0 && is_file($path) && time() - filemtime($path) < $t) {
        // cache còn hạn
        return true;
    }
    // cache hết hạn
    return false;
}

// tạo key cho redis cache từ file name
function WGR_redis_key($f)
{
    // dùng redis thì cắt bỏ đuôi txt cho nhẹ
    // echo $f . '<br>' . "\n";
    $f = str_replace('.', '-', explode('.txt', basename($f))[0]);
    // echo $f . '<br>' . "\n";
    if (defined('EB_PREFIX_CACHE')) {
        return EB_PREFIX_CACHE . $f;
    }
    return $f;
}

function WGR_my_cache($path, $c = '', $t = 120)
{
    // TEST
    // return false;

    // $by_line = '¦';
    $by_line = '|WGR_CACHE|';
    //die($path);

    // có nội dung thì lưu file
    if ($c != '') {
        if (EB_CDN_UPLOADS_URL != '') {
            // thay đường dẫn cho file tĩnh trong thư mục uploads
            $c = str_replace(DYNAMIC_BASE_URL . 'wp-content/uploads/', EB_CDN_UPLOADS_URL . 'wp-content/uploads/', $c);
            // thay đường dẫn cho file tĩnh trong thư mục themes -> lỗi CORS -> bỏ
            // $c = str_replace(DYNAMIC_BASE_URL . 'wp-content/themes/', EB_CDN_UPLOADS_URL . 'wp-content/themes/', $c);
        }

        //
        $t *= 1;
        // cache qua redis (nếu có)
        if (EB_REDIS_CACHE == true) {
            $rd = new Redis();
            $rd->connect(REDIS_MY_HOST, REDIS_MY_PORT);
            // echo "Connection to server sucessfully";
            $rd_key = WGR_redis_key($path);
            // echo $rd_key;

            // try catch
            try {
                // key will be deleted after 10 seconds
                $rd->setex($rd_key, $t, $c);
            } catch (Exception $e) {
                // set the data in redis string
                $rd->set($rd_key, $c);
                // key will be deleted after 10 seconds
                $rd->expire($rd_key, $t);
            }
            return true;
        }
        $c = (time() + $t) . $by_line . $c;
        return WGR_create_file($path, $c);
    }

    // cache qua redis (nếu có)
    if (EB_REDIS_CACHE == true) {
        $rd = new Redis();
        $rd->connect(REDIS_MY_HOST, REDIS_MY_PORT);
        // echo "Connection to server sucessfully";
        // Get the stored data and return it 
        return $rd->get(WGR_redis_key($path));
    }
    // không có nội dung thì kiểm tra hạn cache
    else if (is_file($path)) {
        return WGR_check_cache_content(explode($by_line, file_get_contents($path, 1), 2));
    }

    // mặc định trả về false
    return false;
}

function WGR_check_cache_content($content)
{
    // không chuẩn cache thì báo false
    if (count($content) != 2 || !is_numeric($content[0])) {
        return false;
    }

    // cọn hạn thì trả về nội dung
    if (($content[0] * 1) > time()) {
        return $content[1];
    }
    return false;
}

function WGR_display($f)
{
    // Don't cache POST requests
    if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
        return false;
    }

    // Check for WordPress auth cookies
    foreach ($_COOKIE as $cookie_name => $cookie_value) {
        // Nếu có cookie đăng nhập thì không sử dụng cache
        if (strpos($cookie_name, 'wordpress_logged_in_') === 0) {
            return false;
        }
    }

    // cache qua redis (nếu có)
    if (EB_REDIS_CACHE == true) {
        $rd = new Redis();
        $rd->connect(REDIS_MY_HOST, REDIS_MY_PORT);
        // echo "Connection to server sucessfully";
        // Get the stored data and print it 
        $data = $rd->get(WGR_redis_key($f));
        // var_dump($data);
        // echo "Stored string in redis: " . $data;
        // die(WGR_redis_key($f));
        if ($data === false) {
            return false;
        }
        // echo __FILE__ . ':' . __LINE__ . '<br>' . "\n";

        // với redis cache thì print ra luôn
        header('X-Cache: HIT from Redis');
        echo $data;
        echo '<!-- generated by ebsuppercache (using redis) -->';
        exit();
    } else if (!is_file($f)) {
        return false;
    } else {
        // còn không thì cache qua file
        $data = file_get_contents($f, 1);
    }
    //die(__FILE__ . ':' . __LINE__);

    //
    // $content = explode('¦', $data, 2);
    $content = explode('|WGR_CACHE|', $data, 2);
    if (count($content) < 2 || !is_numeric($content[0])) {
        return false;
    }
    $reset_time = mt_rand(1, 30);
    $active_reset = ($content[0] * 1) - time() - $reset_time;
    //echo $active_reset . '<br>' . "\n";
    //echo $reset_time . '<br>' . "\n";
    //die(__FILE__ . ':' . __LINE__);
    if ($active_reset < 0) {
        return false;
    }

    // -> done
    header('X-Cache: HIT from Disk');
    echo $content[1];
    echo '<!-- generated by ebsuppercache (' . $active_reset . ' | ' . $reset_time . ' | ' . date('Y-m-d H:i:s', $content[0]) . ') -->';
    exit();
}

//
function WGR_get_cache_file($cache_dir = '')
{
    if (isset($GLOBALS['wgr_cache_key']) && $GLOBALS['wgr_cache_key'] != '') {
        $uri = $GLOBALS['wgr_cache_key'];
    } else {
        if (isset($_SERVER['REQUEST_URI'])) {
            $uri = $_SERVER['REQUEST_URI'];
            // echo $uri . '<br>' . "\n";
        } else {
            $uri = $_SERVER['SCRIPT_NAME'];
            $uri .= (!empty($_SERVER['QUERY_STRING'])) ? '?' . $_SERVER['QUERY_STRING'] : '';
            // echo $uri . '<br>' . "\n";
        }

        // Nếu là trang chủ thì đổi tên file cache
        if ($uri == '/' || $uri == '') {
            $uri = '-';
            // } else if (1 > 2 && defined('WGR_IS_HOME')) {
            // $uri = WGR_IS_HOME;
        } else {
            // echo $uri . '<br>' . "\n";
            // loại bỏ các tham số không cần thiết như fbclid, gclid, fb_comment_id, utm_source, utm_medium, utm_campaign...
            $uri = preg_replace('/([&?]fbclid|gclid|fb_comment_id|add_to_wishlist|_wpnonce|v|utm_source|utm_medium|utm_campaign)=[^&]+(&|$)/', '', $uri);
            // $uri = rtrim($uri, '&?');
            // echo $uri . '<br>' . "\n";

            // Xử lý HTML entities và URL encoding bị lỗi
            // &amp; → &
            // &amp%3B → &
            $uri = str_replace(['&amp;', '&amp%3B'], '&', $uri);

            // URL decode để xử lý các ký tự encoded
            // $uri = urldecode($uri);
            // echo $uri . '<br>' . "\n";

            // Chuyển về lowercase
            $uri = strtolower($uri);

            // Chỉ giữ lại: a-z, 0-9, -
            $uri = preg_replace('/[^a-z0-9\-]/', '-', $uri);

            // Loại bỏ nhiều dấu - liên tiếp
            $uri = preg_replace('/-+/', '-', $uri);

            // Loại bỏ dấu - ở đầu/cuối
            $uri = trim($uri, '-');
            // echo $uri . '<br>' . "\n";

            // Xử lý đặc biệt cho trang chủ
            if ($uri == '') {
                $uri = '-';
            }
            // Giới hạn độ dài (Redis key nên < 256 chars)
            else if (strlen($uri) > 200) {
                // Nếu quá dài: lấy 180 ký tự đầu + md5(phần còn lại)
                $uri = substr($uri, 0, 180) . '-' . md5(substr($uri, 180));
            }
            // echo $uri . '<br>' . "\n";
        }
    }

    //
    if ($cache_dir != '') {
        $cache_dir .= '/';
    }
    // $uri = EB_THEME_CACHE . $cache_dir . $uri;
    $uri = EB_THEME_CACHE . $cache_dir . $uri . '.txt';
    // echo $uri . '<br>' . "\n";

    //
    return $uri;
}

// thêm câu báo rằng đang lấy nội dung trong cache
function WGR_builder_eb_cache_note($note = '')
{
    return '<!-- Plugin by daidq - Theme by itvn9online
Cached page generated by WGR Cache (ebcache), an product of EB
Served from: ' . EB_PREFIX_CACHE . ':' . $_SERVER['REQUEST_URI'] . ' on ' . date('Y-m-d H:i:s') . '
Served to: ebcache all URI (' . $note . ')
Storage time: ' . EB_TIME_CACHE . '
Caching using ' . (EB_REDIS_CACHE == true ? 'redis' : 'hard disk') . ' drive. Recommendations using SSD for your website.
Compression = gzip -->';
}

// tạo file cache cho các tùy biến trong ux builder
function my_builder_path_cache($fname)
{
    if (defined('EB_THEME_CACHE')) {
        // return EB_THEME_CACHE . $fname;
        return EB_THEME_CACHE . $fname . '.txt';
    }
    return '';
}
